### ISSUE TITLE
Bring LUA page to this repo (staging)

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/www_threefold.io#212]
Bring the LUA page to this repo.
Implement all featured on staging right now.

**Comment by ehab-hassan** [comment]
@robvanmieghem I checked with Mr.conflict and he told me if we do that we need to change the name of repo because Lua doc loader doesn't support dot at repo name(www_threefold.io)
and why we do that while we have repo ready under the same organization (threefoldfoundation) with staging and can go production?

**Comment by VonSub** [comment]
ok, let's make the LUA page 100% reflect what we have in staging now so we can test
